# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: Reorder Areas

# Attribute name
nameFrom: name

# Model Class name
modelClass: Klubitus\Forum\Models\Area

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar
